# Inserts a blank line between shell prompts
add_newline = true

format = """
$character\
$username \
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$deno\
$golang\
$lua\
$nodejs\
$rust\
$custom\
$jobs:: """

[username]
format="[$user]($style)"
style_user="#f54290"
show_always=true

[character]
success_symbol = "[➜](#00bf00) "
vicmd_symbol = "[➜](#0000ff) "
error_symbol = "[✗](#ff0000) "

[line_break]
disabled = true

[aws]
disabled = true

[battery]
disabled = true

[cmake]
disabled = true

[conda]
disabled = true

[crystal]
disabled = true

[dart]
disabled = true

[deno]
disabled = true

[dotnet]
disabled = true

[elm]
disabled = true

[python]
disabled = true

[jobs]
disabled = true

[hg_branch]
disabled = true

[docker_context]
disabled = true

[time]
disabled = true

[env_var]
disabled = true

[erlang]
disabled = true

[gcloud]
disabled = true

[golang]
disabled = true

[helm]
disabled = true

[java]
disabled = true

[julia]
disabled = true

[kotlin]
disabled = true

[kubernetes]
disabled = true

[lua]
disabled = true

[memory_usage]
disabled = true

[nim]
disabled = true

[nix_shell]
disabled = true

[nodejs]
disabled = true

[ocaml]
disabled = true

[openstack]
disabled = true

[package]
disabled = true

[perl]
disabled = true

[php]
disabled = true

[purescript]
disabled = true

[rlang]
disabled = true

[red]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[scala]
disabled = true

[shell]
disabled = true

[shlvl]
disabled = true

[singularity]
disabled = true

[status]
disabled = true

[swift]
disabled = true

[terraform]
disabled = true

[vagrant]
disabled = true

[vlang]
disabled = true

[vcsh]
disabled = true

[zig]
disabled = true

